### ISSUE TITLE
Hour 00-09 cannot be set

### ISSUE THREAD

**Issue by emulated24** [Erriez/ErriezDS1307#3]
Hi, this routine is giving me error in Platform IO for ESP32 Devkit:

```
...
uint8_t gv_hour;
ErriezDS1307 rtc;
Wire.begin();
Wire.setClock(100000);

if (!rtc.setDateTime(08, 55, 00,  25, 11, 2021, 4)) {
...
```

_invalid digit "8" in octal constant
invalid octal digit_

If I set the hour to 8, then the function doesn't work at all and throws error.
Only setting hours from 10-23 works fine.
Same goes for minutes and seconds...
Can you please help me overcome this little issue?

**Comment by Erriez** [comment]
@emulated24 Thanks for using my library. Can you change `08` to `8` and let me know if this works for you?

**Comment by emulated24** [comment]
Hi Erriez,
nope, as I mentioned:
"If I set the hour to 8, then the function doesn't work at all and throws error."

Not sure how to set the time with zero or single digit. Perhaps I'm doing something wrong...

**Comment by Erriez** [comment]
Hi @emulated24,

The compiler generates a correct error, because all DS1307 clock interface functions requires integer notation. 

`08` is not correct to set a date/time:

```
ErriezDS1307SetGetDateTime:68:26: error: invalid digit "8" in octal constant
     if (!rtc.setDateTime(08, 34, 56,  31, 12, 2020, 0)) {
                          ^~
exit status 1
invalid digit "8" in octal constant
```

The example [ErriezDS1307SetGetDateTime](https://github.com/Erriez/ErriezDS1307/blob/master/examples/ErriezDS1307SetGetDateTime/ErriezDS1307SetGetDateTime.ino) with `master` and Arduino UNO:

`if (!rtc.setDateTime(8, 34, 56,  31, 12, 2020, 0)) {`

```
Sketch uses 5362 bytes (16%) of program storage space. Maximum is 32256 bytes.
Global variables use 404 bytes (19%) of dynamic memory, leaving 1644 bytes for local variables. Maximum is 2048 bytes.
```

**Comment by emulated24** [comment]
Hi mate,
yes, I tried that, but it's giving me an error on ESP32. Function doesn't work for some reason.
I am trying to find out what is the culprit.

If the format above works for you and time is set correctly, I guess the problem is on my end.

**Comment by Erriez** [comment]
[ErriezDS1307SetGetDateTime.ino](https://github.com/Erriez/ErriezDS1307/blob/master/examples/ErriezDS1307SetGetDateTime/ErriezDS1307SetGetDateTime.ino) on ESP32 `LOLIN D32` board and DS1307 RTC:

**Correct code with hours in decimal notation:**
```c++
    // Set date/time: 8:34:56 3 December 2021 Friday
    if (!rtc.setDateTime(8, 34, 56,  2, 12, 2021, 5)) {
        Serial.println(F("Set date/time failed"));
    }
```

Output:

```bash
Erriez DS1307 read example
Fri Dec 2 8:34:56 2021
Fri Dec 2 8:34:57 2021
Fri Dec 2 8:34:58 2021
```

Print hours in two digits `08:xx:xx` notation, add the code with a `+` below:
```c++
+   // Print time
+   if (hour < 10) {
+       Serial.print(F("0"));
+   }
    Serial.print(hour);
```

Output:
```
Erriez DS1307 read example
Fri Dec 2 08:34:56 2021
Fri Dec 2 08:34:57 2021
Fri Dec 2 08:34:58 2021
```

I'll close this issue as the reported problem is located in user code, not in this library or in examples.
